//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaDbContext : DbContext
    {
        public CinemaDbContext()
            : base("name=CinemaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catagory> Catagory { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<PersonPrivateDetails> PersonPrivateDetailsSet { get; set; }
    }
}
