//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDb
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Purchase = new HashSet<Purchase>();
        }
    
        public int number { get; set; }
        public string name { get; set; }
        public System.DateTime movie_date { get; set; }
        public int num_of_seat { get; set; }
        public double ticket_price { get; set; }
        public int p_year { get; set; }
        public int length { get; set; }
        public string poster_url { get; set; }
        public int catagory_id { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchase { get; set; }
    }
}
