//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPrivateDetails
    {
        public string user_name { get; set; }
        public string passward { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
