//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int purchase_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> number { get; set; }
        public System.DateTime purchase_date { get; set; }
        public int purchase_amount { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Person Person { get; set; }
    }
}
